export { createCapsules, type CreateCapsulesOptions } from "./core/capsules.js";
export { CapsuleError, type CapsuleErrorCode } from "./core/errors.js";

export type {
  CapsuleAdapter,
  CapsuleDedupe,
  CapsuleEffectRecordInput,
  CapsuleEffectRef,
  CapsuleEffectSnapshot,
  CapsuleEffectSnapshotOptions,
  CapsuleEffects,
  CapsuleFailure,
  CapsuleFileBody,
  CapsuleFileOptions,
  CapsuleFileRef,
  CapsuleFiles,
  CapsuleRefs,
  CapsuleRunContext,
  CaptureOptions,
  CapsuleSpec,
  CapsulesService,
  InspectedRun,
  StandardSchemaV1,
  CloudflareAdapter,
  MemoryAdapter,
  LocalAdapter,
  RemoteAdapter,
  WorkflowEventLike,
  WorkflowStepContextLike,
} from "./core/types.js";
